import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle2', timeout: 30000 });
await new Promise(r => setTimeout(r, 3000));
await page.evaluate(() => window.scrollTo(0, 1566));
await new Promise(r => setTimeout(r, 500));
const scrolled = await page.evaluate(() => window.scrollY);
console.log('Actually scrolled to:', scrolled);
const outPath = './temporary screenshots/screenshot-43-tb-fullvp.png';
await page.screenshot({ path: outPath });
console.log('Saved:', outPath);
await browser.close();
